import { Camera } from '../types/cctv';

export const DEFAULT_CAMERAS: Camera[] = [
  {
    id: 'cam-1',
    name: 'CAM-01: Estacionamiento Sup / Mid',
    x: 650,
    y: 300,
    angle: 216,
    reach: 207,
    fov: 65,
    type: 'Fija',
    status: 'active',
    zone: 'Estacionamiento',
    conduit: 'Caja Condulet LL = 1'
  },
  {
    id: 'cam-2',
    name: 'CAM-02: Trailer Médico / Bodega (Izq)',
    x: 490,
    y: 540,
    angle: 215,
    reach: 170,
    fov: 65,
    type: 'Fija',
    status: 'active',
    zone: 'Áreas Verdes / Estacionamiento',
    conduit: 'Caja Condulet LR = 1'
  },
  {
    id: 'cam-3',
    name: 'CAM-03: Trailer Médico / Motos (Der)',
    x: 490,
    y: 540,
    angle: 313,
    reach: 174,
    fov: 65,
    type: 'Fija',
    status: 'active',
    zone: 'Áreas Verdes / Motos',
    conduit: 'Manguera Metálica 3/4"'
  },
  {
    id: 'cam-4',
    name: 'CAM-04: Portón PCP / Nómina',
    x: 850,
    y: 290,
    angle: 211,
    reach: 208,
    fov: 65,
    type: 'PTZ',
    status: 'active',
    zone: 'Portón Acceso PCP',
    conduit: 'Caja Condulet Tipo T = 1+1'
  },
  {
    id: 'cam-5',
    name: 'CAM-05: PCP Av. Intercomunal',
    x: 860,
    y: 290,
    angle: 328,
    reach: 208,
    fov: 65,
    type: 'PTZ',
    status: 'active',
    zone: 'PCP / Entrada',
    conduit: 'Caja Condulet T'
  },
  {
    id: 'cam-6',
    name: 'CAM-06: Entrada Estac. Transporte',
    x: 860,
    y: 300,
    angle: 45,
    reach: 220,
    fov: 70,
    type: 'Domo',
    status: 'active',
    zone: 'Estacionamiento Transporte',
    conduit: 'Tubo Metálico 3/4"'
  },
  {
    id: 'cam-7',
    name: 'CAM-07: Estac. Transporte Norte-Der',
    x: 1540,
    y: 300,
    angle: 205,
    reach: 160,
    fov: 70,
    type: 'Domo',
    status: 'active',
    zone: 'Estacionamiento Transporte',
    conduit: 'Caja Condulet LR'
  },
  {
    id: 'cam-8',
    name: 'CAM-08: Estac. Transporte Sur-Der',
    x: 1540,
    y: 330,
    angle: 135,
    reach: 155,
    fov: 70,
    type: 'Domo',
    status: 'active',
    zone: 'Estacionamiento Transporte',
    conduit: 'Caja Condulet LL'
  },
  {
    id: 'cam-9',
    name: 'CAM-09: Bombonas de Gas',
    x: 1610,
    y: 320,
    angle: 16,
    reach: 160,
    fov: 60,
    type: 'Térmica',
    status: 'active',
    zone: 'Bombonas de Gas',
    conduit: 'Caja Condulet T'
  },
  {
    id: 'cam-1787583753374',
    name: 'CAM-10: Nueva Cámara',
    x: 660,
    y: 310,
    angle: 136,
    reach: 160,
    fov: 60,
    type: 'Fija',
    status: 'active',
    zone: 'Planta Cabudare',
    conduit: 'Caja Condulet T'
  },
  {
    id: 'cam-1787583771299',
    name: 'CAM-11: Nueva Cámara',
    x: 760,
    y: 350,
    angle: 125,
    reach: 130,
    fov: 40,
    type: 'Fija',
    status: 'active',
    zone: 'Planta Cabudare',
    conduit: 'Caja Condulet T'
  },
  {
    id: 'cam-1787583812963',
    name: 'CAM-12: Nueva Cámara',
    x: 490,
    y: 560,
    angle: 119,
    reach: 109,
    fov: 60,
    type: 'Fija',
    status: 'active',
    zone: 'Planta Cabudare',
    conduit: 'Caja Condulet T'
  }
];
